# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/jackpotlte/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter jackpotlte, $(TARGET_DEVICE)),)

include $(call all-makefiles-under,$(LOCAL_PATH))

endif